"""add task status creation/update datetime for tasks

Revision ID: 0f209bf1fef1
Revises: cdfc7a14efe7
Create Date: 2024-01-27 20:21:19.742105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f209bf1fef1'
down_revision: Union[str, None] = 'cdfc7a14efe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_status', sa.String(length=64), nullable=True))
    op.add_column('task', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('task', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'updated_at')
    op.drop_column('task', 'created_at')
    op.drop_column('task', 'task_status')
    # ### end Alembic commands ###
