"""squash migrations

Revision ID: 12e0a5a60474
Revises: 
Create Date: 2025-01-27 18:26:52.286974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12e0a5a60474'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('datasource', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('id', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('datasource', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('id', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sprint',
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('datasource', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('id', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('datasource', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('id', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('gid', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('datasource', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('id', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('project_id', sa.String(length=1024), nullable=False),
    sa.Column('sprint_id', sa.String(length=1024), nullable=True),
    sa.Column('task_status', sa.String(length=64), nullable=True),
    sa.Column('story_points', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('assignee_id', sa.String(length=1024), nullable=True),
    sa.Column('external_dependency_id', sa.String(length=1024), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('datasource', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('id', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['external_dependency_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_labels',
    sa.Column('task_id', sa.String(length=1024), nullable=True),
    sa.Column('label_id', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE')
    )
    op.create_index(op.f('ix_task_labels_label_id'), 'task_labels', ['label_id'], unique=False)
    op.create_index(op.f('ix_task_labels_task_id'), 'task_labels', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_labels_task_id'), table_name='task_labels')
    op.drop_index(op.f('ix_task_labels_label_id'), table_name='task_labels')
    op.drop_table('task_labels')
    op.drop_table('task')
    op.drop_table('user')
    op.drop_table('status')
    op.drop_table('sprint')
    op.drop_table('project')
    op.drop_table('label')
    # ### end Alembic commands ###
