"""add label entity

Revision ID: 22ba4ab57e63
Revises: 3691fbc7634f
Create Date: 2025-01-27 13:37:14.376309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ba4ab57e63'
down_revision: Union[str, None] = '3691fbc7634f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('datasource', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('id', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_labels',
    sa.Column('task_id', sa.String(length=1024), nullable=True),
    sa.Column('label_id', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE')
    )
    op.create_index(op.f('ix_task_labels_label_id'), 'task_labels', ['label_id'], unique=False)
    op.create_index(op.f('ix_task_labels_task_id'), 'task_labels', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_labels_task_id'), table_name='task_labels')
    op.drop_index(op.f('ix_task_labels_label_id'), table_name='task_labels')
    op.drop_table('task_labels')
    op.drop_table('label')
    # ### end Alembic commands ###
