"""add gid in user entity

Revision ID: 3691fbc7634f
Revises: c107093e22bc
Create Date: 2025-01-26 10:45:26.464752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3691fbc7634f'
down_revision: Union[str, None] = 'c107093e22bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gid', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gid')
    # ### end Alembic commands ###
