"""add transition entity

Revision ID: ab965ed3280a
Revises: c27f261f80bc
Create Date: 2025-01-25 16:05:37.213616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab965ed3280a'
down_revision: Union[str, None] = 'c27f261f80bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transition',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('datasource', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('id', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transition')
    # ### end Alembic commands ###
