"""rename transition entity

Revision ID: c107093e22bc
Revises: ab965ed3280a
Create Date: 2025-01-25 16:14:39.079672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c107093e22bc'
down_revision: Union[str, None] = 'ab965ed3280a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('datasource', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('id', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('transition')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transition',
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('external_id', sa.VARCHAR(length=256), nullable=False),
    sa.Column('datasource', sa.VARCHAR(length=256), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=256), nullable=False),
    sa.Column('id', sa.VARCHAR(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('status')
    # ### end Alembic commands ###
