"""add task story points

Revision ID: dc4be0cb8fa5
Revises: 22ba4ab57e63
Create Date: 2025-01-27 18:04:30.992285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc4be0cb8fa5'
down_revision: Union[str, None] = '22ba4ab57e63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('story_points', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'story_points')
    # ### end Alembic commands ###
